# Generated by Django 6.0.7 on 2026-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='phase',
            field=models.CharField(blank=True, choices=[('prelims', 'Prelims'), ('mains', 'Mains'), ('interview', 'Interview')], max_length=10),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
