# Generated by Django 6.0.7 on 2026-07-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_dailytask_phase_dailytask_priority'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to='tracker.tracker'),
        ),
    ]
