# Generated by Django 6.0.7 on 2026-07-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_dailytask_tracker'),
        ('study', '0004_alter_topic_options_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='study.topic'),
        ),
    ]
