# Generated by Django 6.0.7 on 2026-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
        ('study', '0003_remove_topic_is_completed_subject_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionschedule',
            name='confidence',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AddField(
            model_name='revisionschedule',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisionschedule',
            name='stage',
            field=models.PositiveSmallIntegerField(default=1, help_text='Revision round: R1 through R5.'),
        ),
        migrations.RemoveField(
            model_name='revisionschedule',
            name='stage_days',
        ),
        migrations.AlterUniqueTogether(
            name='revisionschedule',
            unique_together={('topic', 'stage')},
        ),
    ]
