# Generated by Django 6.0.7 on 2026-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='quote_shown',
            field=models.BooleanField(default=False),
        ),
    ]
