# Generated by Django 6.0.7 on 2026-07-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginsession_quote_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_study_target_minutes',
            field=models.PositiveIntegerField(default=240),
        ),
    ]
