# Generated by Django 6.0.7 on 2026-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_daily_study_target_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=64),
        ),
    ]
