# Generated by Django 6.0.7 on 2026-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='hours_collected',
            field=models.BooleanField(default=False),
        ),
    ]
