# Generated by Django 6.0.7 on 2026-07-12 14:53

import apps.routines.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_minutes', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('minutes_spent', models.PositiveSmallIntegerField(default=0)),
                ('logged_time', models.TimeField(default=apps.routines.models.default_logged_time)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='routines.routine')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('routine', 'date')},
            },
        ),
    ]
