# Generated by Django 6.0.7 on 2026-07-13 16:47

import apps.tracker.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('boolean', 'Yes / No'), ('duration', 'Duration (minutes)'), ('count', 'Count')], default='boolean', max_length=10)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(default='bi-check2-circle', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('logged_time', models.TimeField(default=apps.tracker.models.default_logged_time)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.tracker')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('tracker', 'date')},
            },
        ),
    ]
