# Generated by Django 6.0.7 on 2026-07-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='category',
            field=models.CharField(choices=[('custom', 'Custom'), ('health', 'Health')], default='custom', max_length=10),
        ),
    ]
