# Generated by Django 6.0.7 on 2026-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_topic_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='subject',
            name='phase',
            field=models.CharField(blank=True, choices=[('prelims', 'Prelims'), ('mains', 'Mains'), ('interview', 'Interview')], max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='confidence',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='topic',
            name='weightage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
