# Generated by Django 6.0.7 on 2026-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_topic_options_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
