# Generated by Django 6.0.7 on 2026-07-13 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='phase',
            field=models.CharField(choices=[('prelims', 'Prelims'), ('mains', 'Mains'), ('interview', 'Interview')], default='prelims', max_length=10),
        ),
        migrations.CreateModel(
            name='TestGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_score', models.PositiveSmallIntegerField(default=100)),
                ('target_accuracy', models.PositiveSmallIntegerField(default=70)),
                ('next_test_date', models.DateField(blank=True, null=True)),
                ('next_test_name', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
