# Generated by Django 6.0.7 on 2026-07-26 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0005_topic_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#0d6efd', max_length=20)),
                ('icon', models.CharField(default='bi-bookmark', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('goal_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('on_break', 'On Break'), ('wasting', 'Wasting Time'), ('closed', 'Closed')], default='idle', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('goal_minutes', models.PositiveIntegerField()),
                ('completed_minutes', models.PositiveIntegerField(default=0)),
                ('missed_minutes', models.PositiveIntegerField(default=0)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('waste_minutes', models.PositiveIntegerField(default=0)),
                ('completion_percent', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_sessions', to=settings.AUTH_USER_MODEL)),
                ('daily_timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timetracker.dailytimer')),
            ],
            options={
                'ordering': ['-start_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('daily_timer',), name='one_open_break_per_daily_timer')],
            },
        ),
        migrations.CreateModel(
            name='TimerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('day_started', 'Day Started'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('break_started', 'Break Started'), ('break_ended', 'Break Ended'), ('waste_started', 'Waste Started'), ('waste_ended', 'Waste Ended'), ('day_closed', 'Day Closed')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetracker.activity')),
                ('daily_timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timetracker.dailytimer')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['user', 'daily_timer', 'occurred_at'], name='timetracker_user_id_415b1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetracker.activity')),
                ('daily_timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='timetracker.dailytimer')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timer_sessions', to='study.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timer_sessions', to='study.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['user', 'start_at'], name='timetracker_user_id_986dac_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('daily_timer',), name='one_open_timersession_per_daily_timer')],
            },
        ),
        migrations.CreateModel(
            name='WasteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('daily_timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='timetracker.dailytimer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('daily_timer',), name='one_open_waste_per_daily_timer')],
            },
        ),
    ]
