# Generated by Django 6.0.7 on 2026-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('study', 'Study'), ('tuition', 'Tuition'), ('break', 'Break'), ('others', 'Others'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
        migrations.AddField(
            model_name='breaksession',
            name='planned_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytimer',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('on_break', 'On Break'), ('closed', 'Closed')], default='idle', max_length=10),
        ),
    ]
